// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThucTap.Models;

#nullable disable

namespace ThucTap.Migrations
{
    [DbContext(typeof(ThucTapDbContext))]
    [Migration("20240410145045_tuyendungadd")]
    partial class tuyendungadd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ThucTap.Models.BaiViet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ChuDeID")
                        .HasColumnType("int");

                    b.Property<bool>("HienThi")
                        .HasColumnType("bit");

                    b.Property<bool>("KiemDuyet")
                        .HasColumnType("bit");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TieuDeKhongDau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TomTat")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.HasKey("ID");

                    b.HasIndex("ChuDeID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("BaiViet", (string)null);
                });

            modelBuilder.Entity("ThucTap.Models.BinhLuanBaiViet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BaiVietID")
                        .HasColumnType("int");

                    b.Property<bool>("KiemDuyet")
                        .HasColumnType("bit");

                    b.Property<int>("LuotXem")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungBinhLuan")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.HasKey("ID");

                    b.HasIndex("BaiVietID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("BinhLuanBaiViet", (string)null);
                });

            modelBuilder.Entity("ThucTap.Models.ChuDe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenChuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenChuDeKhongDau")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("ChuDe", (string)null);
                });

            modelBuilder.Entity("ThucTap.Models.DichVu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("LoaiDichVuID")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("TenDV")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("LoaiDichVuID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("DichVu", (string)null);
                });

            modelBuilder.Entity("ThucTap.Models.LoaiDichVu", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID");

                    b.ToTable("LoaiDichVu", (string)null);
                });

            modelBuilder.Entity("ThucTap.Models.NguoiDung", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Quyen")
                        .HasColumnType("bit");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("ThucTap.Models.TuyenDung", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TuyenDung", (string)null);
                });

            modelBuilder.Entity("ThucTap.Models.BaiViet", b =>
                {
                    b.HasOne("ThucTap.Models.ChuDe", "ChuDe")
                        .WithMany("BaiViet")
                        .HasForeignKey("ChuDeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThucTap.Models.NguoiDung", "NguoiDung")
                        .WithMany("BaiViet")
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuDe");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ThucTap.Models.BinhLuanBaiViet", b =>
                {
                    b.HasOne("ThucTap.Models.BaiViet", "BaiViet")
                        .WithMany("BinhLuanBaiViet")
                        .HasForeignKey("BaiVietID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThucTap.Models.NguoiDung", "NguoiDung")
                        .WithMany("BinhLuanBaiViet")
                        .HasForeignKey("NguoiDungID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiViet");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ThucTap.Models.DichVu", b =>
                {
                    b.HasOne("ThucTap.Models.LoaiDichVu", "LoaiDichVu")
                        .WithMany("DichVu")
                        .HasForeignKey("LoaiDichVuID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThucTap.Models.NguoiDung", null)
                        .WithMany("DichVu")
                        .HasForeignKey("NguoiDungID");

                    b.Navigation("LoaiDichVu");
                });

            modelBuilder.Entity("ThucTap.Models.BaiViet", b =>
                {
                    b.Navigation("BinhLuanBaiViet");
                });

            modelBuilder.Entity("ThucTap.Models.ChuDe", b =>
                {
                    b.Navigation("BaiViet");
                });

            modelBuilder.Entity("ThucTap.Models.LoaiDichVu", b =>
                {
                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("ThucTap.Models.NguoiDung", b =>
                {
                    b.Navigation("BaiViet");

                    b.Navigation("BinhLuanBaiViet");

                    b.Navigation("DichVu");
                });
#pragma warning restore 612, 618
        }
    }
}
